### ISSUE TITLE
Update npgw-api-specification for customerDetails.state

### ISSUE THREAD

**Issue by ViktoriyaED** [NPGW/npgw-api-specification#11]
- Required for US (Mainland US states) and Canada: The state must be a 2-letter uppercase string.

- Optional for other countries (excluding US and Canada): The state can be an optional field.
The field should accept Latin alphabetic letters and diacritics.

**Comment by LukieNumbrSlevin** [comment]
https://github.com/NPGW/npgw-api-specification/pull/15
